### ISSUE TITLE
Error with P1 MacOS setup

### ISSUE THREAD

**Issue by arun-annamalai** [eecs485staff/issues#26]
Project 1

## Describe the bug
https://eecs485staff.github.io/p1-insta485-static/setup_os.html

Bug is found in the Macos setup portion of P1 of 485. Link above. 

A quote from the setup.
```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
$ brew install python3 git tree wget
$ brew cask install java
$ which python3
/usr/local/bin/python3
$ python3 --version # python 3.6+ is required
Python 3.8.6
```
The error is with brew cask install java which does not work. Steps 1 and 2 work. 

## To Reproduce
Steps to reproduce the behavior.
1. Type in terminal $ brew cask install java
2. get error "Calling brew cask install is disabled! Use brew install [--cask] instead."
3. Type in terminal $ brew install --cask java
4. get error "Cask 'java' is unavailable: No Cask with this name exists. "

## Expected behavior
Java should be installed.

**Comment by awdeorio** [comment]
Can you try `brew install java` and see if that works?  Report back and we can modify the instructions!

**Comment by arun-annamalai** [comment]
works perfectly! thanks for rapid the fix

**Comment by awdeorio** [comment]
I'm going to reopen this issue so we can correct the instructions.  CC @jkloosterman @jadchaar
