### ISSUE TITLE
Possible Bug in Project 1 Spec

### ISSUE THREAD

**Issue by zhiyuanw101** [eecs485staff/issues#27]
## Current language

>  $ cp -R html/css/ insta485/static/
>  $ cp -R html/images/ insta485/static/

## Problem
These two commands seem can not create the following directory tree. The `cp` command specifies that the source path end with '/' copies the contents of the directory are copied rather than the directory itself. 

## Proposed language

Change
>  $ cp -R html/css/ insta485/static/
>  $ cp -R html/images/ insta485/static/

To
>  $ cp -R html/css insta485/static/
>  $ cp -R html/images insta485/static/

**Comment by awdeorio** [comment]
I can confirm that this is the case with BSD `cp`, e.g., the one shipped by default with macOS.  However, GNU `cp` shipped with Linux works fine.

CC @jadchaar

**Comment by jadchaar** [comment]
Submitted a PR to get this fixed in p1 repo!

**Comment by seshrs** [comment]
This is fixed now, closing this issue. Thanks for reporting @zhiyuanw101!
