### ISSUE TITLE
Lab 4 Question 2

### ISSUE THREAD

**Issue by saputran** [eecs485staff/issues#28]
Lab 4 Question 2 (sorry I'm not familiar with GitHub so I'm not sure what it means by add this to the side bar)

Hi,

I hope you're doing well! I had a question on Piazza about Lab 4, Question 2 (where it asks about turning Google's background black). For this question, I assumed it meant to change it for everyone since it mentioned Google's background (while the other options didn't mention Google itself at all which means it was talking about the copy). I didn't receive a response on my Piazza post clarifying if this meant the background for all users or just the copied file until after the quiz was due (@1015), and so Professor Kloosterman directed me to submit this form. Would it be possible to gain credit for this question with this assumption since I received clarification after the quiz deadline?

Thank you and please let me know!
~ Natasha Saputra

**Comment by seshrs** [comment]
Hi @saputran! I think Prof. Kloosterman was referring to this form: https://docs.google.com/forms/d/e/1FAIpQLSciss60Z4_u2_VNQ725tBtTEpWwlz02zbF8gn3v2wleWkvA1A/viewform

Would you be able to contact the staff via that form? This repo is used to document issues related to the specs for projects and labs, so I’m going to close this issue for now. Feel free to follow up if you have questions! :)

CC @jkloosterman
