### ISSUE TITLE
p1-insta485generator use instructor's config.json instead of student's

### ISSUE THREAD

**Issue by Northbadge** [eecs485staff/issues#32]
> Which project?  Add a GitHub label using the side bar, then delete this. 

We don't have permissions to apply labels

## Describe your suggestion
> What do you think we should add?

Have the autograder scripts which use `insta485generator` overwrite student's `config.json` file with a fresh/expected copy before running `insta485generator`

## Motivation
> How would your suggestion improve the project and improve student learning?

Currently if students change `config.json` (whether that be for experimenting or debugging) and forgot to revert those changes before submitting to the AG, they would fail some test cases since the generated pages don't match what the AG scripts expect. For private test cases specifically, students wouldn't know till the deadline has past.

**Comment by awdeorio** [comment]
Moved relevant info to issue in private repo
