### ISSUE TITLE
p1-spec more direct verbose examples

### ISSUE THREAD

**Issue by Northbadge** [eecs485staff/issues#33]
Which project?  Add a GitHub label using the side bar, then delete this.

### Verbose
>Here’s an example of the --verbose (-v) option.
>>$ rm -rf hello/html
>>$ insta485generator hello --verbose
>>Rendered index.html -> hello/html/index.html
>
>Here’s a slightly more complicated example with a static CSS style file. The hello_css/ example is provided with the starter files.
>.... (a lot of stuff)
>
>>$ pytest -v tests/test_insta485generator_hello_css.py
>>============================= test session starts ==============================
>>...
>>
>>::test_index PASSED                                                      [100%]
>>
>>============================== 1 passed in 0.77s ===============================

## Problem
Too much info in verbose subheader

#### Change verbose subheader to
>Here’s an example of the --verbose (-v) option with the previous two examples.
>>$ rm -rf hello/html
>>$ insta485generator hello --verbose
>>**Rendered index.html -> hello/html/index.html**
>
>>$ rm -rf hello_css/html
>>$ insta485generator -v hello_css
>>**Copied hello_css/static -> hello_css/html**
>>**Rendered index.html -> hello_css/html/index.html**
>
> (Bolded for emphasis only, you shouldn't bold your output)
>
> You can find a more complicated example of the verbose option in the....... (as before)

#### Move the below `hello_css` section to a new subheader "A more complicated example"(?) and place it before the jinja subheader, and remove the -v flag (and its output) from the example
>Here’s a slightly more complicated example with a static CSS style file. The hello_css/ example is provided with the starter files.
>.... (a lot of stuff)
>
>>$ pytest -v tests/test_insta485generator_hello_css.py
>>============================= test session starts ==============================
>>...
>>
>>::test_index PASSED                                                      [100%]
>>
>>============================== 1 passed in 0.77s ===============================

#### Why
Makes it very clear what verbose should output, instead of burying its output in the middle of a codeblock (and file contents) as it is now

**Comment by awdeorio** [comment]
This is done!  New version here: https://eecs485staff.github.io/p1-insta485-static/
