### ISSUE TITLE
Insta485run script spec error

### ISSUE THREAD

**Issue by kyschnit** [eecs485staff/issues#36]
Project 2 spec

## Current language
> Write script called bin/insta485run that runs the development server.
> If var/insta485.sqlite3 does not exist, print an error and exit non-zero.

## Problem
test_scripts.py fails if you follow this language. Instead of printing an error and exiting non-zero if ```insta485.sqlite3``` does not exist  you must run ```insta485db create``` instead.

## Proposed language

Change
> If var/insta485.sqlite3 does not exist, print an error and exit non-zero.

To
> If var/insta485.sqlite3 does not exist, create the database and proceed.

(or, change test_scripts.py to follow what the spec says)

**Comment by noah-weingarden** [comment]
Hi @kyschnit, thanks for submitting an issue! Could you please clarify when you downloaded the starter files? I suspect you may have a very outdated copy of them.

**Comment by kyschnit** [comment]
You're right - I replaced the starter files with the new ones and I pass test_scripts.py locally now when exiting 1. However, when I submit to the autograder, I time out on test_scripts.py (specifically on test_insta485run). When I submitted to the autograder with my old code (which did not exit 1 and instead created the database), my code passed test_insta485run.

**Comment by noah-weingarden** [comment]
@MattyMay says the autograder hasn't been updated to the most recent version of that test yet, but just that test. It should be fixed soon if it hasn't been already. Thanks for bringing this up!
