### ISSUE TITLE
dayjsjs Typo in EECS 485 P3

### ISSUE THREAD

**Issue by andydrewwm** [eecs485staff/issues#38]
**Describe the bug**
Typo in EECS 485 Project 3 spec. In the [Human readable timestamps](https://eecs485staff.github.io/p3-insta485-clientside/#human-readable-timestamps) section, there is a typo in the second sentence. It reads:

> Use the [`dayjsjs`](https://day.js.org/en/) library. . .

**To Reproduce**
1. Go to [Human readable timestamps](https://eecs485staff.github.io/p3-insta485-clientside/#human-readable-timestamps) section of EECS 485 Project 3.
2. Find the second sentence.
3. See error "`dayjsjs`"

**Expected behavior**
`dayjsjs` should be `dayjs`

**Screenshots**
![image](https://github.com/eecs485staff/primer-spec/assets/129251843/7cc9af74-edd5-4942-b4bd-39ac5e997575)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 117.0.5938.134

**Comment by seshrs** [comment]
Thanks for reporting, @andydrewwm!

CC @awdeorio, @MattyMay, @melodell 

EDIT: Looks like @noah-weingarden has a fix up already 👍
