### ISSUE TITLE
MapReduce walkthrough chart final output file has "part-" + {4 digits} instead of 5 digits

### ISSUE THREAD

**Issue by jadonniels** [eecs485staff/issues#41]
Project 4, no option to add a project in the side bar(?), it was seemingly just the text "None yet"

## Current language
Wherever the MapReduce flowchart is shown. Most relevant after:
>This section describes the Reduce Stage in the flowchart, shown with purple boxes.

## Problem
The final output files in the example read 'part-0000' and 'part-0001' instead of using 5 digits as is described in the spec.

## Proposed language
Change the output files to 'part-00000' and 'part-00001' respectively.

In flowchart:
Change
> part-0000
> part-0001

To
> part-00000
> part-00001

**Comment by awdeorio** [comment]
Thanks for filing an issue @jadonniels .  I'll ask @meha-goyal to fix this and update the spec.
