### ISSUE TITLE
Website Icon for Spec (all)

### ISSUE THREAD

**Issue by denalym** [eecs485staff/issues#42]
Side bar isn't letting me change labels :(

## Favicon for Project Specification Pages
I think it would be a nice quality of life feature for the project specifications to include a favicon or website icon in the tab. This would not be a high priority feature at all but at the same time I believe it is simple enough to make it possibly worthwhile despite this fact.

## Motivation
When working on the project, I noticed that there is no special icon in the tab for EECS 485 projects. See below:

<img width="68" alt="image" src="https://github.com/eecs485staff/issues/assets/112737694/9db9e854-4d68-4ca3-a991-ceee3a899e9e"> \
*Figure 1: p4-mapreduce spec as it could appear in a student's browser*       
   
  
Compare this to some previous courses, which include an icon identifying the course as the favicon for their project specifications:

<img width="72" alt="image" src="https://github.com/eecs485staff/issues/assets/112737694/35305e13-65e6-4b79-b1a0-f938fb747f6f"> \
*Figure 2: project specification for a different course displaying the course image as the tab icon*

<img width="68" alt="image" src="https://github.com/eecs485staff/issues/assets/112737694/01b70a55-22be-45d8-8d36-680985857bf5"> \
*Figure 3: project specification for a third course displaying the course image as the tab icon*

While the lack of this feature does not significantly negatively impact the learning experience, here are a few reasons I believe the addition of one might be considered.
1. During a coding session, a student may have a large number of tabs open. These may include the project specification, EECS 485 tutorials, tutorials from other classes (many courtesy of Professor DeOrio), Piazza, one or more papers or notes documents regarding relevant topics, and so forth. By adding a unique favicon for EECS 485 project specifications, it will be easier for students to identify the location of the project specification tab (arguably the most important one) at a glance or by color. This could save time spent searching through tabs or clicking on the wrong tab and trying again.
2. The course website already has a simple, clear icon which is aesthetically pleasing and also based on a pun. Creating a sense of connection and unity within course resources as well as having a personal touch in the student interface can make the course feel more welcoming for students. The icon for a project specification need not be the same as that for the course website, but it is certainly one possibility.
3. To the extent of my knowledge (which is quite limited, so this may be an inaccurate judgment) it does not take a large amount of effort to add a favicon to a project specification page. The main change required appears to be the addition of a line in the `_config.yml` file. Thus, it can be justifiable to add such an unimportant feature.

**Comment by seshrs** [comment]
Thanks for reporting the issue, @denalym! (And I'm glad you did your research and learned more about [Primer Spec](https://github.com/eecs485staff/primer-spec) 😃 )

The project websites do actually specify a favicon already! If you "View Source" for any of the spec websites, you'll find this line:
```html
<link rel="icon" href="https://eecs485staff.github.io/eecs485.org/favicon.ico">
```

But as you pointed out, the favicon doesn't display. Turns out that the favicon URL is obsolete 😢 
```console
$ http -h --follow https://eecs485staff.github.io/eecs485.org/favicon.ico
HTTP/1.1 404 Not Found
...
```

If we view the source for [eecs485.org](https://eecs485.org), it looks like the new favicon URL is https://eecs485staff.github.io/eecs485.org/assets/images/eecs485favicon.ico

---

I'll go ahead and put up diffs to fix the favicon URL in the EECS 485 spec 👍

**Comment by denalym** [comment]
Thanks for the deeper breakdown of what's going on here! Definitely seeing how the concepts learned in the beginning of the class apply. The primer spec is widely used now, including by the staff team I am on, so it's helpful to learn more about it.

**Comment by awdeorio** [comment]
I think this is resolved by the 5 PRs that @seshrs posted.  Please reopen this issue if I missed anything.
