### ISSUE TITLE
EECS 280 Primer Spec

### ISSUE THREAD

**Issue by skomariv** [eecs485staff/issues#8]
This command has deprecated: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)". It should be replaced with /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)". Additionally, "brew install wget git tree" is not enough to link homebrew's compiler to MacOS original one. You must also enter these two commands after "alias gcc='gcc-10'
alias g++='g++-10'" to get an updated g++ compiler. (Details from this post: https://stackoverflow.com/questions/50501388/how-to-update-g-compiler-on-osx)

**Comment by seshrs** [comment]
Oh wait, I think the 280 setup tutorial has similar instructions. https://eecs280staff.github.io/p1-stats/setup.html#macos

It seems to be in response to post [@]69 on the 280 Piazza?

CC @awdeorio

**Comment by awdeorio** [comment]
Fixed in EECS 280 repo!
