### ISSUE TITLE
Spec task list formatting

### ISSUE THREAD

**Issue by aposp** [eecs485staff/issues#9]
Which project?  Add a GitHub label using the side bar, then delete this.
p1-insta485-static
(my github view doesn't show any sidebar, sorry)

## Current language

> We will now begin implementing the functionality for our insta485generator. We will modify __main__.py to take in Jinja templates and render them. The key things that you will need to implement for this part are
>
>1) Handle command line arguments using the click library 2) Render the provided templates and write them to output files and create all the necessary directories and files needed to do this 3) Copy over a static directory if it is provided 4) Handle errors
>
>The inputs to insta485generator are templated HTML files with data in JSON format. The output will be pure HTML files.

[The "1)" at the start of the list formats as a numbered bullet in markdown]

## Problem
Not a problem necessarily, but formatting an important checklist of project tasks in this one-line format seems unnecessarily confusing.

## Proposed language

> We will now begin implementing the functionality for our insta485generator. We will modify __main__.py to take in Jinja templates and render them. The key things that you will need to implement for this part are:
>
>
> 1. Handle command line arguments using the click library
> 2. Render the provided templates and write them to output files and create all the necessary directories and files needed to do this
> 3. Copy over a static directory if it is provided
> 4. Handle errors

>
>The inputs to insta485generator are templated HTML files with data in JSON format. The output will be pure HTML files.

I'm sure an unnumbered list would be fine as well.

**Comment by awdeorio** [comment]
Thanks for the clear issue!  This is fixed and published.  https://eecs485staff.github.io/p1-insta485-static/
